### ISSUE TITLE
AuthorizesResources should be removed since Laravel 5.3

### ISSUE THREAD

**Issue by cristianuibar** [ied3vil/LanguageSwitcher#11]
From the upgrade guides: The AuthorizesResources Trait

The AuthorizesResources trait has been merged with the AuthorizesRequests trait. You should remove the AuthorizesResources trait from your app/Http/Controllers/Controller.php file.

![image](https://user-images.githubusercontent.com/1476365/30523880-315a9080-9bf2-11e7-8320-ae0d33ebeb8e.png)

**Comment by Niremizov** [comment]
https://github.com/ied3vil/LanguageSwitcher/pull/12

**Comment by cristianuibar** [comment]
How does fixing the readme headers solve this issue?

**Comment by Niremizov** [comment]
Sorry, wrong issue number, must be referenced to https://github.com/ied3vil/LanguageSwitcher/issues/8
Btw this issue fixed  in https://github.com/ied3vil/LanguageSwitcher/commit/c383ce069d6b95ca46357eb63c62c11a939bb895 just use master@dev.

**Comment by cristianuibar** [comment]
I see. Thanks for pointing that out. I'll close this considering it's already been fixed.
