### ISSUE TITLE
Trait 'Illuminate\Foundation\Auth\Access\AuthorizesResources' not found

### ISSUE THREAD

**Issue by ghost** [ied3vil/LanguageSwitcher#14]
On new laravel that the "Trait 'Illuminate\Foundation\Auth\Access\AuthorizesResources' not found" error is thrown since the AuthorizesResources trait has been merged with the AuthorizesRequests trait. Should remove the AuthorizesResources trait from file.

**Comment by ied3vil** [comment]
I believe I have fixed this in a pull request that I have merged a while back

**Comment by herrwalter** [comment]
Got the same problem here, would be nice to get fixed.

**Comment by ghost** [comment]
@ied3vil i think the pull is still open https://github.com/ied3vil/LanguageSwitcher/pull/12

**Comment by ied3vil** [comment]
#12 was just readme.md fixes!

https://github.com/ied3vil/LanguageSwitcher/pull/2 is the fix that was merged

**Comment by herrwalter** [comment]
Please create a tag/release for this merge request. We now have to depend on the master. @ied3vil

**Comment by ied3vil** [comment]
@herrwalter added tagged version 1.1.1 that includes the fix. If you need anything else let me know
