### ISSUE TITLE
How to call setLanguage?

### ISSUE THREAD

**Issue by Masegi** [ied3vil/LanguageSwitcher#16]
Hi,

first thanks for your package - nice work, thanks alot.

But how do I change the lang by code?

I tried 
LanguageSwitcher::setLanguage($language)
but I get this message:
Non-static method ied3vil\LanguageSwitcher\LanguageSwitcherController::setLanguage() should not be called statically

I use newest laravel - what am I doing wrong?

Thanks alot.
Regards matthias

**Comment by Masegi** [comment]
nvm, it's \ied3vil\LanguageSwitcher\Facades\LanguageSwitcher::setLanguage

**Comment by ied3vil** [comment]
Glad you sorted it!

If you import (use statement) the facade at the top of the php file, you will be able to write LanguageSwitcher::...
