### ISSUE TITLE
Unable to locate publishable resources.

### ISSUE THREAD

**Issue by OfficialCRUGG** [ied3vil/LanguageSwitcher#20]
Hey there! When trying to run the publish Command with the provider Parameter, I get a message saying "Unable to locate publishable resources.". When I'm doing it without, I just don't see the Package as an option.

**Comment by maarten00** [comment]
The solution is pretty simple. Since this package is not auto-discoverable by Laravel, you just have to register the service provider before running the publish command. 
In `app.php` in `providers` add the following line:
```php
        ied3vil\LanguageSwitcher\Providers\LanguageSwitcherProvider::class,
```
