### ISSUE TITLE
Fatal Error with Laravel 5.3

### ISSUE THREAD

**Issue by herzcthu** [ied3vil/LanguageSwitcher#3]
FatalErrorException in LanguageSwitcherController.php line 16: Trait 'Illuminate\Foundation\Auth\Access\AuthorizesResources' not found

Please see this
http://stackoverflow.com/questions/37625522/trait-illuminate-foundation-auth-access-authorizesresources-not-found

**Comment by ied3vil** [comment]
did you follow the suggestions on stackoverflow? updating composer and 
the framework?

----------------------------------

Mit freundlichen Grüßen/With best regards/Cu stima,
Marian Razvan-Cristian
Senior Software Developer


==============================
Manchester, UK
Yahoo Messenger ID: ied3vil
Skype ID: ied3vil
e-mail: ied3vil@gmail.com
==============================

**Comment by galpratama** [comment]
I also getting the same error. I removing the `AuthorizesResources` and it seems to work

**Comment by herzcthu** [comment]
https://github.com/ied3vil/LanguageSwitcher/blob/1.1.0/src/ied3vil/LanguageSwitcher/LanguageSwitcherController.php

Version 1.1.0 still include AthorizesResources.
Using dev-master fix the problem.

**Comment by ied3vil** [comment]
Is this still an issue?

**Comment by aauerswald** [comment]
I'm using Laravel 5.4 and I have the same issue.

FatalErrorException in LanguageSwitcherController.php line 16:
Trait 'Illuminate\Foundation\Auth\Access\AuthorizesResources' not found

composer self-update
composer update
composer clearcache

is done.

When I remove AuthizesResources from line 16 i got the following error:

FatalErrorException in Manager.php line 138:
Call to undefined method Illuminate\Session\Store::set()

Please help!

Thanks and best regards

Solution: I changes composer.json to "dev-master" -> fixed the problem....

**Comment by erik-ropez** [comment]
@ied3vil There is no stable release for 5.3/5.4, thus users are pushed to use dev-master.

**Comment by liteylgay** [comment]
Could you please indicate how to change composer.json to dev-master? Thanks!

**Comment by erik-ropez** [comment]
@liteylgay, should be
```
"require" : {
    ...
    "ied3vil/language-switcher": "dev-master",
    ...
},
"minimum-stability": "dev",
```

**Comment by liteylgay** [comment]
Thanks a lot! 
I actually changed the line  41 in LanguageSwitcher.php
Session::set($this->getLanguageKey(), $language);
To 
Session::put($this->getLanguageKey(), $language);

And it worked. I'll also switch to dev-master.

**Comment by mramadanhamza** [comment]
php artisan clear-cache
php artisan clear-compiled
etc... and
composer dump-autoload
etc...
