### ISSUE TITLE
Laravel 5.4 and Session::set

### ISSUE THREAD

**Issue by brugner** [ied3vil/LanguageSwitcher#4]
Hi, for me to work in Laravel 5.4 I had to change Session::set to Session::put, take a look:

/**
     * Sets the language flag and returns the cookie to be created on the redirect
     * @param $language
     * @return mixed | null
     */
    public function setLanguage($language)
    {
           if ($this->getStorageMethod() == 'cookie') {
               return cookie()->forever($this->getLanguageKey(), $language);
           }

           Session::put($this->getLanguageKey(), $language);
           $this->registerLanguage();
           return cookie('dummy-cookie', FALSE, 1); //just for cleaner code in the controller
    }

Can you confirm this is an error? 
Thank you!

**Comment by ied3vil** [comment]
Hello you are correct
I have to add a new version to the library to take Laravel 5.4's changes

**Comment by brugner** [comment]
Awesome! Thank you for developing this, is very useful and easy to use!

**Comment by ied3vil** [comment]
This is fixed
