### ISSUE TITLE
Laravel 5.4 Many issues

### ISSUE THREAD

**Issue by rafaelxavierborges** [ied3vil/LanguageSwitcher#6]
First of all sorry my poor english. Let's continue:

Found one issue running Laravel 5.4.*.

Warning:
The AuthorizesResources trait has been merged with the AuthorizesRequests trait.
So, in \vendor\ied3vil\language-switcher\src\ied3vil\LanguageSwitcher\LanguageSwitcherController.php
you'll have to remove this line bellow:

use Illuminate\Foundation\Auth\Access\AuthorizesResources;

AND need to change this line bellow:

from: use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
to:      use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

But the LanguageSwitcher actually doesn't switch the language.
When a link like  {{ url('/lang/es') }} is clicked, nothing happens.
No actions, no errors, just redirect()->back() to main url '/'.

Can you help me?

**Comment by erik-ropez** [comment]
You should probably use dev-master branch as it has changes for recent Laravel version. It works on 5.4 for me. And I use "cookie" mode - locale is switching.

**Comment by erik-ropez** [comment]
One note about "cookie" mode. It has a flaw - if cookie is not set then empty locale is used. I've created 
 #7 pull request to fix this.

**Comment by ied3vil** [comment]
@erik-ropez i have just merged your pull request because it made sense

@rafaelxavierborges let me know if you still have problems
