### ISSUE TITLE
Laravel 5.5 support

### ISSUE THREAD

**Issue by royduin** [ied3vil/LanguageSwitcher#8]
Please add Laravel 5.5 support (auto package discovery) and create a new version. And maybe fix the markdown in de readme?

**Comment by ied3vil** [comment]
I will try to find time next week.
What's wrong with the markdown in the readme?

**Comment by royduin** [comment]
The headings, for example these:

<img width="233" alt="schermafbeelding 2017-09-01 om 12 46 04" src="https://user-images.githubusercontent.com/1703233/29966748-90d7adcc-8f13-11e7-8ed5-864fcff4bed6.png">

Just one space between `##` and the heading text should do it.

**Comment by Niremizov** [comment]
https://github.com/ied3vil/LanguageSwitcher/pull/12

**Comment by ied3vil** [comment]
Fixed the headings

**Comment by royduin** [comment]
Thanks! But the headings are fixed but still no auto package discovery support for Laravel 5.5 and after that; please tag a new version.
